PATTERNS = {
#Halves - 4
"E1/2":  ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE"],
"W1/2":  ["NWNW","NENW","SWNW","SENW","NWSW","NESW","SWSW","SESW"],
"S1/2":  ["NWSW","NESW","SWSW","SESW","NWSE","NESE","SWSE","SESE"],
"N1/2":  ["NWNW","NENW","SWNW","SENW","NWNE","NENE","SWNE","SENE"],

#Quarters - 4
"NW1/4":  ["NWNW","NENW","SWNW","SENW"],
"NE1/4":  ["NWNE","NENE","SWNE","SENE"],
"SW1/4":  ["NWSW","NESW","SWSW","SESW"],
"SE1/4":  ["NWSE","NESE","SWSE","SESE"],

#Half Quarters - 16
"W1/2NW1/4":  ["NWNW","SWNW"],
"E1/2NW1/4":  ["NENW","SENW"],
"N1/2NW1/4":  ["NWNW","NENW"],
"S1/2NW1/4":  ["SWNW","SENW"],
"W1/2NE1/4":  ["NWNE","SWNE"],
"E1/2NE1/4":  ["NENE","SENE"],
"N1/2NE1/4":  ["NWNE","NENE"],
"S1/2NE1/4":  ["SWNE","SENE"],
"W1/2SW1/4":  ["NWSW","SWSW"],
"E1/2SW1/4":  ["NESW","SESW"],
"N1/2SW1/4":  ["NWSW","NESW"],
"S1/2SW1/4":  ["SWSW","SESW"],
"W1/2SE1/4":  ["NWSE","SWSE"],
"E1/2SE1/4":  ["NESE","SESE"],
"N1/2SE1/4":  ["NWSE","NESE"],
"S1/2SE1/4":  ["SWSE","SESE"],

#Half Halves - 8
"W1/2W1/2":  ["NWNW","SWNW","NWSW","SWSW"],
"E1/2W1/2":  ["NENW","SENW","NESW","SESW"],
"W1/2E1/2":  ["NWNE","SWNE","NWSE","SWSE"],
"E1/2E1/2":  ["NENE","SENE","NESE","SESE"],
"N1/2N1/2":  ["NWNW","NENW","NWNE","NENE"],
"S1/2N1/2":  ["SWNW","SENW","SWNE","SENE"],
"N1/2S1/2":  ["NWSW","NESW","NWSE","NESE"],
"S1/2S1/2":  ["SWSW","SESW","SWSE","SESE"],

#Quarter Quarters - 16
"NW1/4NW1/4":  ["NWNW"],
"NE1/4NW1/4":  ["NENW"],
"SW1/4NW1/4":  ["SWNW"],
"SE1/4NW1/4":  ["SENW"],
"NW1/4NE1/4":  ["NWNE"],
"NE1/4NE1/4":  ["NENE"],
"SW1/4NE1/4":  ["SWNE"],
"SE1/4NE1/4":  ["SENE"],
"NW1/4SW1/4":  ["NWSW"],
"NE1/4SW1/4":  ["NESW"],
"SW1/4SW1/4":  ["SWSW"],
"SE1/4SW1/4":  ["SESW"],
"NW1/4SE1/4":  ["NWSE"],
"NE1/4SE1/4":  ["NESE"],
"SW1/4SE1/4":  ["SWSE"],
"SE1/4SE1/4":  ["SESE"],

#<<<<<<<<<<<<<<<  FOLLOWING NEED VALUES ASSIGNED!   >>>>>>>>>>>>>>>
'2E':  ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE"],
'2N':  ["NWNW","NENW","SWNW","SENW","NWNE","NENE","SWNE","SENE"],
'2NE':  ["NWNE","NENE","SWNE","SENE"],
'2NW':  ["NWNW","NENW","SWNW","SENW"],
'2S':  ["NWSW","NESW","SWSW","SESW","NWSE","NESE","SWSE","SESE"],
'2SE':  ["NWSE","NESE","SWSE","SESE"],
'2SESE':  ["SESE"],
'2SW':  ["NWSW","NESW","SWSW","SESW"],
'2SWSW':  ["SWSW"],
'2W':  ["NWNW","NENW","SWNW","SENW","NWSW","NESW","SWSW","SESW"],
'4NE':  ["NWNE","NENE","SWNE","SENE"],
'4SE':  ["NWSE","NESE","SWSE","SESE"],
'4SW':  ["NWSW","NESW","SWSW","SESW"],
'E':  ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE"],
'E/2':  ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE"],
'E/2SE':  ["NESE","SESE"],
'E2':  ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE"],
'E2E2':  ["NENE","SENE","NESE","SESE"],
# 'E2E2NE':  [],
# 'E2E2NENE':  [],
# 'E2E2NW':  [],
# 'E2E2SE':  [],
# 'E2E2SENWSE':  [],
# 'E2E2SW':  [],
# 'E2E2SWNE':  [],
# 'E2E2W2':  [],
# 'E2E2W2NE':  [],
'E2N2':  ["NENE", "NENW", "NESE", "NESW"],
'E2NE':  ["NENE", "SENE"],
'E2NE4':  ["NENE", "SENE"],
# 'E2NESE':  [],
# 'E2NESW':  [],
'E2NW':  ["NENW", "SENW"],
'E2NW4':  ["NENW", "SENW"],
# 'E2NWNE':  [],
# 'E2NWNW':  [],
# 'E2NWNWSE':  [],
# 'E2NWSE':  [],
# 'E2NWSW':  [],
'E2SE':  ["NESE", "SESE"],
'E2SE4':  ["NESE", "SESE"],
# 'E2SENE':  [],
# 'E2SENW':  [],
# 'E2SESE':  [],
# 'E2SESW':  [],
'E2SW':  ["NESW", "SESW"],
'E2SW4':  ["NESW","SESW"],
# 'E2SW4SW4':  [],
# 'E2SWNW':  [],
# 'E2SWSE':  [],
# 'E2SWSW':  [],
'E2W':  ["NENW", "SENW", "NESW", "SESW"],
'E2W2': ["NENW", "SENW", "NESW", "SESW"],
# 'E2W2NE':  [],
# 'E2W2SWSE':  [],
# 'E3SE':  [],
'N':  ["NWNW","NENW","SWNW","SENW","NWNE","NENE","SWNE","SENE"],
'N2':  ["NWNW","NENW","SWNW","SENW","NWNE","NENE","SWNE","SENE"],
'N2E2':  ["NENE", "NWNE", "SWNE", "SENE"],
'N2N2':  ["NWNW", "NENW", "NWNE", "NENE"],
# 'N2N2N2':  [],
# 'N2N2N2N2':  [],
# 'N2N2NE':  [],
# 'N2N2NW':  [],
# 'N2N2NWNW':  [],
# 'N2N2S2':  [],
# 'N2N2SE':  [],
# 'N2N2SW':  [],
# 'N2N3':  [],
'N2NE':  ["NENE", "NWNE"],
'N2NE4':  ["NENE", "NWNE"],
# 'N2NENE':  [],
# 'N2NENW':  [],
# 'N2NESE':  [],
# 'N2NESW':  [],
'N2NW':  ["NWNW", "NENW"],
'N2NW4':  ["NWNW", "NENW"],
# 'N2NWNE':  [],
# 'N2NWSW':  [],
# 'N2NWSWSE':  [],
'N2S2':  ["NWSW", "NESW", "NWSE", "NESE"],
# 'N2S2NE':  [],
# 'N2S2NENE':  [],
# 'N2S2NW':  [],
# 'N2S2SE':  [],
# 'N2S2SW':  [],
'N2SE':  ["NWSE", "NESE"],
'N2SE4':  ["NWSE", "NESE"],
# 'N2SE4SE4':  [],
# 'N2SENE':  [],
# 'N2SENESE':  [],
# 'N2SENW':  [],
# 'N2SESE':  [],
# 'N2SESW':  [],
# 'N2SESWNE':  [],
'N2SW':  ["NWSW", "NESW"],
'N2SW4':  ["NWSW", "NESW"],
# 'N2SWNE':  [],
# 'N2SWNW':  [],
# 'N2SWSE':  [],
# 'N2SWSW':  [],
# 'N2SWSWSE':  [],
# 'N2SWSWSW':  [],
'N2W2':  ["NWNW", "NENW", "SENW", "SWNW"],
'NE':  ["NWNE","NENE","SWNE","SENE"],
'NE4':  ["NWNE","NENE","SWNE","SENE"],
'NE4NE4':  ["NENE"],
'NE4NW4':  ["NENW"],
'NE4SE4':  ["NESE"],
'NE4SW4':  ["NESW"],
'NENE':  ["NENE"],
# 'NENENE':  [],
# 'NENENENE':  [],
# 'NENESE':  [],
'NENW':  ["NENW"],
# 'NENWNE':  [],
# 'NENWNW':  [],
# 'NENWSE':  [],
# 'NENWSW':  [],
'NESE':  ["NESE"],
'NESW':  ["NESW"],
# 'NESWNE':  [],
# 'NESWNW':  [],
# 'NESWSE':  [],
'NW':  ["NWNW","NENW","SWNW","SENW"],
'NW4':  ["NWNW","NENW","SWNW","SENW"],
'NW4NE4':  ["NWNE"],
'NW4NW4':  ["NWNW"],
'NW4SE4':  ["NWSE"],
'NW4SW4':  ["NWSW"],
'NWNE':  ["NWNE"],
# 'NWNENE':  [],
'NWNW':  ["NWNW"],
# 'NWNWNE':  [],
# 'NWNWNESE':  [],
# 'NWNWNW':  [],
# 'NWNWSE':  [],
'NWSE':  ["NWSE"],
# 'NWSENW':  [],
'NWSW':  ["NWSW"],
# 'NWSWNESE':  [],
# 'NWSWNESW':  [],
# 'NWSWNW':  [],
# 'NWSWSE':  [],
# 'NWSWSW':  [],
'S':  ["NWSW","NESW","SWSW","SESW","NWSE","NESE","SWSE","SESE"],
'S2':  ["NWSW","NESW","SWSW","SESW","NWSE","NESE","SWSE","SESE"],
'S25':  ["NWSW","NESW","SWSW","SESW","NWSE","NESE","SWSE","SESE"],
'S2E2':  ["NWSE", "SWSE", "NESE", "SESE"],
'S2N2':  ["SWNW", "SENW", "SWNE", "SENE"],
# 'S2N2N2N2NE':  [],
# 'S2N2N2N2NENW':  [],
# 'S2N2N2NE':  [],
# 'S2N2N2NENW':  [],
# 'S2N2NE':  [],
# 'S2N2NENW':  [],
# 'S2N2NWSE':  [],
# 'S2N2S2':  [],
# 'S2N2SE':  [],
# 'S2N2SW':  [],
'S2NE':  ["SWNE", "SENE"],
'S2NE4':  ["SWNE", "SENE"],
# 'S2NENE':  [],
# 'S2NENENE':  [],
# 'S2NENW':  [],
# 'S2NESW':  [],
's2NW':  ["SWNW", "SENW"],
'S2NW4':  ["SWNW", "SENW"],
# 'S2NW4SW4SW4':  [],
# 'S2NWNW':  [],
# 'S2NWSE':  [],
'S2S2':  ["SWSW", "SESW", "SWSE", "SESE"],
# 'S2S2N2NE':  [],
# 'S2S2NW':  [],
# 'S2S2S2':  [],
# 'S2S2S2S2':  [],
# 'S2S2S2S2S2S2S2':  [],
# 'S2S2SE':  [],
# 'S2S2SW':  [],
'S2SE':  ["SWSE", "SESE"],
'S2SE4':  ["SWSE", "SESE"],
# 'S2SE4SE4':  [],
# 'S2SENE':  [],
# 'S2SENW':  [],
# 'S2SENWSE':  [],
# 'S2SESE':  [],
# 'S2SESENW':  [],
# 'S2SESW':  [],
'S2SW':  ["SWSW", "SESW"],
'S2SW4':  ["SWSW", "SESW"],
# 'S2SWNW':  [],
# 'S2SWSE':  [],
# 'S2SWSENW':  [],
# 'S2SWSWSW':  [],
'S2W2':  ["NWSW", "NESW", "SWSW", "SESW"],
'SE':  ["NWSE","NESE","SWSE","SESE"],
'SE4':  ["NWSE","NESE","SWSE","SESE"],
# 'SE4NE4':  [],
# 'SE4NW4':  [],
# 'SE4SE4':  [],
# 'SE4SW4':  [],
'SENE':  ["SENE"],
# 'SENENWNE':  [],
# 'SENESE':  [],
# 'SENESW':  [],
# 'SENEW':  [],
'SENW':  ["SENW"],
# 'SENWNW':  [],
# 'SENWSW':  [],
'SESE':  ["SESE"],
# 'SESENW':  [],
# 'SESESWSW':  [],
'SESW':  ["SESW"],
# 'SESWNE':  [],
# 'SESWSE':  [],
# 'SESWSW':  [],
# 'SESWSWSW':  [],
'SW':  ["NWSW","NESW","SWSW","SESW"],
'Sw1':  ["NWSW","NESW","SWSW","SESW"],
'SW4':  ["NWSW","NESW","SWSW","SESW"],
# 'SW4NE4':  [],
# 'SW4NW4':  [],
# 'SW4SE4':  [],
# 'SW4SW4':  [],
'SWNE':  ["SWNE"],
# 'SWNENE':  [],
# 'SWNENW':  [],
# 'SWNESW':  [],
'SWNW':  ["SWNW"],
# 'SWNWNENE':  [],
# 'SWNWNW':  [],
# 'SWNWNWNW':  [],
'SWSE':  ["SWSE"],
# 'SWSENE':  [],
# 'SWSENW':  [],
'SWSW':  ["SWSW"],
# 'SWSWNE':  [],
# 'SWSWNW':  [],
# 'SWSWNWSE':  [],
# 'SWSWSE':  [],
# 'SWSWSESW':  [],
# 'SWSWSW':  [],
'W':  ["NWNW","NENW","SWNW","SENW","NWSW","NESW","SWSW","SESW"],
'W2':  ["NWNW","NENW","SWNW","SENW","NWSW","NESW","SWSW","SESW"],
'W2E2':  ["NWNE", "SWNE", "NWSE", "SWSE"],
# 'W2E2E2':  [],
# 'W2E2NESE':  [],
# 'W2E2NW':  [],
# 'W2E2SW':  [],
# 'W2E2W2NE':  [],
# 'W2N2N2NWSE':  [],
'W2NE':  ["NWNE", "SWNE"],
'W2NE4':  ["NWNE", "SWNE"],
# 'W2NENE':  [],
# 'W2NENW':  [],
# 'W2NESE':  [],
# 'W2NESW':  [],
'W2NW':  ["NWNW", "SWNW"],
'W2NW4':  ["NWNW", "SWNW"],
# 'W2NWNE':  [],
# 'W2NWNWSE':  [],
# 'W2NWSE':  [],
# 'W2NWSESE':  [],
# 'W2NWSW':  [],
'W2SE':  ["NWSE", "SWSE"],
'W2SE4':  ["NWSE", "SWSE"],
# 'W2SENE':  [],
# 'W2SENW':  [],
# 'W2SESE':  [],
'W2SW':  ["NWSW", "SWSW"],
'W2SW4':  ["NWSW", "SWSW"],
# 'W2SWNE':  [],
# 'W2SWNW':  [],
'W2W2':  ["NWNW", "SWNW", "NWSW", "SWSW"],
# 'W2W2E2NE':  [],
# 'W2W2E2SE':  [],
# 'W2W2NW':  [],
# 'W2W2SE':  [],
# 'W2W2SW':  [],
# 'W2W2W2':  [],
# 'W2W2W2W2W2W2':  [],
# 'W2W2NE':  []




    # All
    # "ALL": ["NWNE","NENE","SWNE","SENE","NWSE","NESE","SWSE","SESE","NWNW","NENW","SWNW","SENW","NWSW","NESW","SWSW","SESW","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"]#
}


# Pattern QA
for key, value in PATTERNS.items():
    if not isinstance(value, list):
        raise TypeError('Pattern values must be list of elements')

    for element in value:
        if len(element) > 4:
            raise ValueError(f'Element(s) seems to be misformed: {key}:{value}. Check that each is a separate string')
